"""Constants for CYD UI."""

DOMAIN = "cyd_ui"
INTEGRATION_NAME = "CYD UI"
PANEL_COMPONENT = "cyd-ui-panel"
PANEL_PATH = "cyd-ui"
PANEL_TITLE = "CYD UI"
PANEL_ICON = "mdi:monitor-dashboard"
STATIC_URL = "/cyd_ui_static"
VERSION = "0.1.0"
